"""add user_id to quizquestion and quizanswer

Revision ID: c5a27a7eba21
Revises: f4cad2ac7691
Create Date: 2025-11-09 15:34:25.139696
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'c5a27a7eba21'
down_revision = 'f4cad2ac7691'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audiosource', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('fk_audiosource_user_id'), 'audiosource', type_='foreignkey')
    op.create_foreign_key(None, 'audiosource', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_generationjob_id'), table_name='generationjob')
    op.drop_index(op.f('ix_generationjob_job_type'), table_name='generationjob')
    op.drop_index(op.f('ix_generationjob_status'), table_name='generationjob')
    op.create_index(op.f('ix_generationjob_audio_source_id'), 'generationjob', ['audio_source_id'], unique=False)
    op.drop_index(op.f('ix_quizanswer_id'), table_name='quizanswer')
    op.drop_index(op.f('ix_quizquestion_id'), table_name='quizquestion')
    op.drop_index(op.f('ix_quizresult_id'), table_name='quizresult')
    op.drop_constraint(op.f('uq_users_email'), 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.drop_constraint(op.f('user_session_token_jti_key'), 'user_session', type_='unique')
    op.create_index(op.f('ix_user_session_token_jti'), 'user_session', ['token_jti'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_session_token_jti'), table_name='user_session')
    op.create_unique_constraint(op.f('user_session_token_jti_key'), 'user_session', ['token_jti'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint(op.f('uq_users_email'), 'user', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_quizresult_id'), 'quizresult', ['id'], unique=False)
    op.create_index(op.f('ix_quizquestion_id'), 'quizquestion', ['id'], unique=False)
    op.create_index(op.f('ix_quizanswer_id'), 'quizanswer', ['id'], unique=False)
    op.drop_index(op.f('ix_generationjob_audio_source_id'), table_name='generationjob')
    op.create_index(op.f('ix_generationjob_status'), 'generationjob', ['status'], unique=False)
    op.create_index(op.f('ix_generationjob_job_type'), 'generationjob', ['job_type'], unique=False)
    op.create_index(op.f('ix_generationjob_id'), 'generationjob', ['id'], unique=False)
    op.drop_constraint(None, 'audiosource', type_='foreignkey')
    op.create_foreign_key(op.f('fk_audiosource_user_id'), 'audiosource', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('audiosource', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
